dist: trusty
sudo: false

language: php
php:
  - 5.6
  - 7

services:
  - mysql

env:
  global:
    - BRANCH=master
  matrix:
    - DB=mysql

matrix:
  include:
    - php: 5.6
      env: DB=mysql BRANCH=stable11
    - php: 5.6
      env: DB=mysql BRANCH=stable12

install:
 - ls
 - which mysql && until mysql -u root -e "show status" &>/dev/null; do sleep 1; done
 - createuser -U travis -s oc_autotest
 - mysql -e 'create database oc_autotest;'
 - mysql -u root -e "CREATE USER 'oc_autotest'@'localhost' IDENTIFIED BY '';"
 - mysql -u root -e "grant all on oc_autotest.* to 'oc_autotest'@'localhost';"
 - cd ..
 - git clone https://github.com/nextcloud/server.git --recursive --depth 1 -b $BRANCH nextcloud
 - mv cloud_user_hiorg nextcloud/apps/user_hiorg
 - ls
 - ./nextcloud/occ maintenance:install --database-name oc_autotest --database-user oc_autotest --database-pass --admin-user admin --admin-pass admin --database $DB
 - ./nextcloud/occ app:enable user_hiorg
 - cd nextcloud/apps/user_hiorg

# Note the install script should make sure we are in the apps/ojsxc directory
script:
  - composer install
  - ./vendor/bin/phpunit -c phpunit.xml --coverage-clover=unit-coverage.xml
  - cat ../../data/nextcloud.log
#  - vendor/bin/php-cs-fixer fix --dry-run --using-cache=no
#  - rm -r vendor/ && ../../occ app:check-code user_hiorg

after_success:
  - bash <(curl -s https://codecov.io/bash)
